# Generated by Django 5.0.4 on 2024-04-18 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_posts", "0002_remove_question_body_question_attempt_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="attempt_body",
        ),
    ]
