# Generated by Django 5.0.4 on 2024-04-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0004_alter_question_image_alter_question_problem_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='problem_body',
            field=models.TextField(null=True),
        ),
    ]
