# Generated by Django 5.0.4 on 2024-04-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0006_question_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
